[template]
cargo_generate_version = ">=0.9.0"

[placeholders]
description = { type="text", prompt="Long description for the crate?" }
ask_for_string = { type="bool", prompt="Make a choice too?", default=true }

[conditional.'ask_for_string'.placeholders.choice]
type = "string"
prompt = "Please select one..."
choices = ["One", "Two", "Three", "Four"]

[conditional.'{ choice == "One" }'.placeholders.styling]
type = "string"
prompt = "How do you want to create CSS?"
choices = ["Tailwind", "Vanilla"]
default = "Vanilla"
