[book]
title = "Cargo Generate Documentation"
description = "cargo, make me a project"
authors = ["The cargo-generate authors"]
language = "en"

[rust]
edition = "2018"

[output.html]
git-repository-url = "https://github.com/cargo-generate/cargo-generate/tree/main/guide"
edit-url-template = "https://github.com/cargo-generate/cargo-generate/edit/main/guide/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
