name: "Combine Dependabot PRs"
on:
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          includeLabel: ""
          ignoreLabel: "nocombine"
          baseBranch: "main"
          openPR: true
          allowSkipped: false
